services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  broker:
    build:
      context: ..
      dockerfile: broker/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: ..
      dockerfile: worker/Dockerfile
    command: python worker.py
    depends_on:
      - redis